version: '3.1'

services:
    app:
        image: nextjs-app
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./pages:/app/pages
            - ./public:/app/public
            - ./styles:/app/styles
